### ISSUE TITLE
Releases中已打包好的程序在哪下载？

### ISSUE THREAD

**Issue by Jimmy73820916** [YXGZCC/-Enterprise-Architect-16-Crack-renewal-#1]

**Comment by YXGZCC** [comment]
GitHub下载地址：https://github.com/YXGZCC/-Enterprise-Architect-16-Crack-renewal-/releases/download/1/EA.1.0-by.exe
国内网盘下载地址：https://yxgz.lanzouq.com/iSr3Q1rtpjob

[Releases]里面应该有打包好的程序下载(https://github.com/YXGZCC/-Enterprise-Architect-16-Crack-renewal-/releases)
